-- 文件说明：为 V1.6 中华整木网自用业务工作台补充客户类型枚举。
-- 功能说明：在不影响 zhengmu-demo 既有客户类型的前提下，为 zhengmu-platform 增加 8 类独立业务客户类型。

ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_FACTORY_OWNER';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_MEMBERSHIP_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_GEO_AI_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_TRAINING_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_EVENT_RESOURCE_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_SUPPLY_CHAIN_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_AFTERMARKET_CLIENT';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'PLATFORM_PARTNER_CLIENT';
